package com.alivanov.intellij.plugins.liquigen.settings;

import com.alivanov.intellij.plugins.liquigen.Extension;
import com.intellij.openapi.ui.ComboBox;
import com.intellij.ui.EnumComboBoxModel;
import com.intellij.ui.components.JBTextField;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class LiquigenSettingsUI {
    private JTextField authorTextField;
    private JComboBox<Extension> formatComboBox;
    private JPanel settingsPanel;

    private LiquigenConfig settingsConfig;

    public JPanel getSettingsPanel() {
        return settingsPanel;
    }

    public LiquigenSettingsUI(LiquigenConfig settingsConfig) {
        this.settingsConfig = settingsConfig;
    }

    public boolean isModified() {
        return !authorTextField.getText().equals(settingsConfig.getAuthor())
                || !formatComboBox.getItemAt(formatComboBox.getSelectedIndex()).equals(settingsConfig.getExtension());
    }

    public void apply() {
        settingsConfig.setAuthor(authorTextField.getText());
        settingsConfig.setExtension(formatComboBox.getItemAt(formatComboBox.getSelectedIndex()));
    }

    public void reset() {
        authorTextField.setText(settingsConfig.getAuthor());
        formatComboBox.setSelectedItem(settingsConfig.getExtension());
    }

    private void createUIComponents() {
        authorTextField = new JBTextField();
        ((JBTextField) authorTextField).getEmptyText().setText(System.getProperty("user.name"));

        formatComboBox = new ComboBox<>(new EnumComboBoxModel<>(Extension.class));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        settingsPanel = new JPanel();
        settingsPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Changeset author:");
        settingsPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        settingsPanel.add(spacer1, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Changeset format:");
        settingsPanel.add(label2, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        settingsPanel.add(authorTextField, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        formatComboBox.setEditable(false);
        formatComboBox.setEnabled(true);
        settingsPanel.add(formatComboBox, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return settingsPanel;
    }
}
